server:
  port: 8084

spring:
  application:
    name: ORDER-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    username: root
    password: vishy
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"

resilience4j:
  circuitbreaker:
    instances:

      paymentService:

        registerHealthIndicator: true

        slidingWindowSize: 10

        minimumNumberOfCalls: 5

        failureRateThreshold: 50

        waitDurationInOpenState: 10s

        permittedNumberOfCallsInHalfOpenState: 3